function instructions(w,bn)
    
    keys=getSettings('keys');
    instruct = {...
    [ ...
%      'You are going to play a number matching game.\n\n',...
%      'Indicate\n\n',...
%      '1 by pushing your INDEX finger \n\n',...
%      '2 by pushing your MIDDLE finger\n\n',...
%      '3 by pushing your RING finger\n\n',...
%      'Always use your right hand'...
%    ],[ ...
      'In the game, you will see three numbers.\n\n',...
      'One of the numbers will be different.\n\n',...
      'always push the button for the DIFFERENT number.'...
    ],[ ...
     'In both of the following examples,\n\n', ...
     '2 is the different number.\n\n', ...
     'The correct response is made by pushing your middle finger'...
    ],[ ...
     '0 2 0'...
    ],[ ...
     '1 1 2'...
    ]...
   };
    
    if bn == 1 || bn >= 4
       instruct = [ ... 
         instruct, ...
          { ...
           [ ...
             'When you see a BLUE crosshair,\n\n',...
             'in addition to pushing the button of the different number,\n\n',...
             'REMEMBER the button you pushed\n\n',...
             '\n', ...
             'Sometimes "XXX" will appear instead of numbers.\n\n' ...
             'You should then push the button you pushed TWO times ago\n\n'...
           ],[ ...
             'In the following example, you would push\n\n',...
             '1, then 2, then 1, then 2' ...
           ],[ ...
             '1 0 0'...
           ],[ ...
             '0 2 0'...
           ],[ ...
             'X X X'...
           ],[ ...
             ''...
           ],[ ...
             'X X X'...
           ],[ ...
             'HINTS:\n\n',...
             'You can forget the number you pushed after you''ve seen two more sets of numbers.\n\n',...
             'You wont ever have to remember the button you pushed durning "XXX"\n\n',...
             'Once you no longer see BLUE crosshairs, you do not have to remember anything\n\n',...
           ]
         } ...
      ];

   
    end 

    KbCheck;
    for i = 1:length(instruct)
      % add newlines for windows
      if ispc
       % instruct{i}=strrep('\n','\n\n');
      end
      DrawFormattedText(w,instruct{i},'center','center',[ 0 0 0 ]);
      Screen('Flip',w);
      WaitSecs(.5);

      [secs, keyCode, deltaSecs] =KbWait;
      escclose(keyCode);
    end
end
