function instructions(w,bn)
    
    keys=getSettings('keys');
    % s.keys.nback  = KbName({'n','b'});
    % %                  index  middle ring
    % s.keys.finger = KbName({'j','k','l'});
    instruct = {...
    [   ...
      keys.string{1} '->' keys.fingernames{1} '\n\n' ...
      keys.string{2} '->' keys.fingernames{2} '\n\n' ...
      keys.string{3} '->' keys.fingernames{3} '\n\n' ...
      '\n'...
    ],[ ...
      'Place your right index, middle, and ring fingers on buttons\n\n'...
      'corresponding to the numbers 1,2,and 3, respectively', ...
    ],[ ...
      'You will then see a row of three numbers,\n\n',...
      'two that are matching and one that is unmatched',...
    ],[ ...
      'On ALL trials, push the button that corresponds\n\n'...
      'to the UNMATCHED number.'...
    ],[ ...
     'In both of the following examles,\n\n'...
     'the correct response is made by pushing your middle finger (2)'...
    ],[ ...
     '3 3 2'...
    ],[ ...
     '0 2 0'...
    ],
    }
    
    if bn == 1 || bn == 4
       instruct = [ instruct, { ...
       [ ...
         'On trials preceded by a blue crosshair,\n\n'...
         'press the key corresponding to the UNMATCHED number \n\n\'...
         'AND hold that number in memory.\n\n'...
         '\n' ...
         'A screen containing "x x x" will sometimes appear.\n\n' ...
         'Respond with the finger corresponding to the unmatched number \n\n'...
         'from two trials previous to the current trial.\n\n' ...
       ],[ ...
        'After an "x x x" screen a new set of 3 numbers will appear.\n\n'...
        'Once again, memorize the UNMATCHED number.\n\n'...
       }];

   
    end 

    KbCheck;
    for i = 1:length(instruct)
      % add newlines for windows
      if ispc
       % instruct{i}=strrep('\n','\n\n');
      end
      DrawFormattedText(w,instruct{i},'center','center',[ 0 0 0 ]);
      Screen('Flip',w);
      WaitSecs(.5);

      [secs, keyCode, deltaSecs] =KbWait;
      escclose(keyCode);
    end
end
