function instructions(w,bn,varargin)
    
    %% should we go threw the examples?
    % yes if
    %   it's pracitce (block less than 1)
    %   or if we ask (with 'example')
    % 
    useexample=any(cellfun(@(x) ~isempty(strmatch(x,'example','exact')), varargin));
    if(bn<1)
     useexample=1;
    end
    bn=abs(bn);

    keys=getSettings('keys');
    instruct = {...
    [ ...
%      'You are going to play a number matching game.\n\n',...
%      'Indicate\n\n',...
%      '1 by pushing your INDEX finger \n\n',...
%      '2 by pushing your MIDDLE finger\n\n',...
%      '3 by pushing your RING finger\n\n',...
%      'Always use your right hand'...
%    ],[ ...
      'In this game, you will see three numbers.\n\n',...
      'One of the numbers will be different.\n\n',...
      'always push the button for the DIFFERENT number.'...
    ]};
    
    if useexample
       instruct = [instruct ,{...
       [ ...
         'In both of the following examples,\n\n', ...
         '2 is the different number.\n\n', ...
         'The correct response is made by pushing your middle finger'...
        ],[ ...
         '0 2 0'...
        ],[ ...
         '1 1 2'...
        ],...
        [ ...
         'If you see a GREEN cross hair,\n\n', ...
         'the correct key will be in the correct position\n\n',...
         '0 2 0\n\n\n',...
         'If you see a RED cross hair,\n\n'...
         'the correct key will not be in the correct position', ...
         '1 1 2\n\n\n',...
       ],...
      }];
    end 

    if bn == 1 || bn >= 4
       instruct = [ ... 
         instruct, ...
          { ...
           [ ...
             'When you see a BLUE crosshair,\n\n',...
             'in addition to pushing the button of the different number,\n\n',...
             'REMEMBER the button you pushed\n\n',...
             '\n', ...
             'Sometimes "XXX" will appear instead of numbers.\n\n' ...
             'You should then push the button you pushed TWO times ago\n\n'...
           ]
          }];

          if useexample
           instruct=[instruct,{[ ...
                'Let''s try an example!',...
              ],[ ...
                '1 0 0'...
              ],[ ...
                '0 2 0'...
              ],[ ...
                'X X X'...
              ],[ ...
                '0 0 3'...
              ],[ ...
                '0 2 0'...
              ],[ ...
                'X X X'...
              ] ...
            } ...
           ];
% HINT removed 20150309 WF, keep queue at 2 always
%              ,[ ...
%                'HINTS:\n\n',...
%                'You can forget the number you pushed after you''ve seen two more sets of numbers.\n\n',...
%                'You wont ever have to remember the button you pushed durning "XXX"\n\n',...
%                'Once you no longer see BLUE crosshairs, you do not have to remember anything\n\n',...
%              ]
          end
   
    end 

    KbCheck;
    for i = 1:length(instruct)
      % add newlines for windows
      if ispc
       % instruct{i}=strrep('\n','\n\n');
      end
      DrawFormattedText(w,instruct{i},'center','center',[ 0 0 0 ]);
      Screen('Flip',w);
      WaitSecs(.5);

      [secs, keyCode, deltaSecs] =KbWait;
      escclose(keyCode);
    end
end
